services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      APP_NAME: ${APP_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_USER_PASSWORD:  ${DB_USER_PASSWORD}
      DB_HOST: ${DB_HOST}